# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200

checkpoint:
  save_interval: 10000 # epoch
  save_interval_updates: 1000
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: wer

task:
  _name: audio_finetuning
  data: ???
  normalize: false
  labels: ltr

dataset:
  num_workers: 6
  max_tokens: 3200000
  skip_invalid_size_inputs_valid_test: true
  validate_after_updates: 0
  validate_interval: 10000 # epoch
  validate_interval_updates: 1000
  valid_subset: dev_other

distributed_training:
  ddp_backend: legacy_ddp
  distributed_world_size: 2

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  max_update: 15000
  lr: [0.00005]
  sentence_avg: true
  update_freq: [4]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

  momentum: 0.9
  weight_decay: 0

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05
  init_lr_scale: 0.01

model:
  _name: wav2vec_ctc
  w2v_path: ???
  apply_mask: true
  mask_prob: 0.65
  mask_channel_prob: 0.25
  mask_channel_length: 64
  layerdrop: 0.1
  dropout: 0.1
  attention_dropout: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 0 # 10000

  checkpoint_activations: false

  prune_rate: 0.9

  no_prune_proj: true
  no_prune_extractor: true
  no_prune_pos: true

  no_prune_post_extract_proj: true

  trainable_if_unpruned: false

  trainable_pos: false
  trainable_proj: false
  trainable_post_extract_proj: false

  trainable_bias: False

  trainable_layer_norm: false
  
  init_score: kaiming_uniform # weight_magnitude

  init_score_scale: 1

  fix_attn: false
  
  fix_fc: false

  layerwise_prune_rate: []

  fc_attn_prune_rate: []

  co_train: false

  ste_sigmoid: false

  ft_fc_only: false
  ft_attn_only: false

  no_pretrained_weights: false

  linear_st_op: 'linear_st'

  fix_mask: false

  fix_mask_before: 0

  load_mask_only: false

  load_mask_before: 0

  use_adapter: False

  adapter_type: 'asr'

  eval_only: false