# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tblog
  seed: 1337

checkpoint:
  save_interval: 1000 # 5
  keep_interval_updates: 1
  no_epoch_checkpoints: false # true
  best_checkpoint_metric: wer

distributed_training:
  ddp_backend: legacy_ddp # c10d
  find_unused_parameters: true
  distributed_world_size: 2 # 1
  distributed_port: 29671
  nprocs_per_node: 1 # 8

task:
  _name: hubert_pretraining
  data: ???
  fine_tuning: true
  label_dir: ???
  normalize: false  # must be consistent with pre-training
  labels: ["ltr"]
  single_target: true

dataset:
  num_workers: 0
  max_tokens: 3200000
  validate_after_updates: ${model.freeze_finetune_updates}
  validate_interval: 10000 # 5
  validate_interval_updates: 1000
  train_subset: train
  valid_subset: valid

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  max_update: 13000
  lr: [0.00005]
  sentence_avg: true
  update_freq: [4] # [1]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

  momentum: 0.9

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05
  init_lr_scale: 0.01

model:
  _name: hubert_ctc
  w2v_path: ???
  apply_mask: true
  mask_selection: static
  mask_length: 10
  mask_other: 0
  mask_prob: 0.75
  mask_channel_selection: static
  mask_channel_length: 64
  mask_channel_other: 0
  mask_channel_prob: 0.5
  layerdrop: 0.1
  dropout: 0.0
  activation_dropout: 0.1
  attention_dropout: 0.0
  feature_grad_mult: 0.0
  freeze_finetune_updates: 0 # 10000

  checkpoint_activations: false

  prune_rate: 0.9

  no_prune_proj: true
  no_prune_extractor: true
  no_prune_pos: true

  no_prune_post_extract_proj: true

  trainable_if_unpruned: false

  trainable_pos: false
  trainable_proj: true
  trainable_post_extract_proj: false

  trainable_bias: False

  trainable_layer_norm: false
  
  init_score: kaiming_uniform # weight_magnitude

  init_score_scale: 1

  fix_attn: true
  
  fix_fc: false

  layerwise_prune_rate: []

  fc_attn_prune_rate: []

  co_train: false

  ste_sigmoid: false

  ft_fc_only: false
  ft_attn_only: false

  no_pretrained_weights: false

  linear_st_op: 'linear_st'

  fix_mask: false

  fix_mask_before: 0

  load_mask_only: false

  load_mask_before: 0


hydra:
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: '__'
        exclude_keys:
          - run
          - task.data
          - task.label_dir
          - model.w2v_path
          - dataset.train_subset
          - dataset.valid_subset
          - criterion.wer_kenlm_model
          - criterion.wer_lexicon
  run:
    dir: ???
  sweep:
    dir: ???
    subdir: ${hydra.job.config_name}__${hydra.job.override_dirname}
